name: Deploy
on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    
    steps:
    # Checkout Repo
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set Up Python Env
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        
    # Installing Python Dependencies
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ".github/workflows/requirements.txt"
      
    # Connect to Snowflake Account
    - name: Initiate Snowflake Connection
      run: python .github/workflows/deploy.py
