name: Deploy
on:
  workflow_run:
    workflows: ["Validate"]
    branches: 
      - 'dev_**'
    types:
      - completed
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Download validation status
      uses: actions/download-artifact@v3
      with:
        name: validation_status
        path: .github/workflows/validation_status.txt
    - name: Set validation status variable
      id: set_validation_status
      run: echo "validation_passed=$(cat .github/workflows/validation_status.txt)" >> $GITHUB_ENV
    - name: Deploy Code
      if: env.validation_passed =='true'
      run: python .github/workflows/deploy.py
