# This is a basic workflow to help you get started with Actions
name: Validate Build
on:
  push:
    branches: 'dev_**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Get SQL Scripts
        id: get-sql-scripts
        run: git ls-files '**.sql' > sql_scripts.txt

      - name: Get Deployment Scripts
        id: get-deployment-scripts
        run: git ls-files '**/all_deployment_scripts/**.sql' > deployment_scripts.

      - name: Execute validation.py
        run: python .github/workflows/validate.py
