# This is a basic workflow to help you get started with Actions
name: Validate Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Get SQL Files
        id: get-sql-files
        run: |
          SQL_FILES=$(git ls-files)
          echo "::set-output
          name=sql_files::$SQL_FILES"

      - name: Loop
        run: |
          for file in ${{ steps.get-sql-files.outputs.sql_files }}
          do 
            echo "Processing file: $file"
          done

      - name: Get Changed files
        id: get-changed-files
        run: |
          git ls-files '*.sql'

      - name: Return files
        run: cat files.txt
