# This is a basic workflow to help you get started with Actions
name: Validate Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Get Branch Name
        run: echo $GITHUB_HEAD_REF

      - name: Get SQL Files
        id: get-sql-files
        run: |
          git ls-files > files.txt

      - name: Execute validation.py
        run: |
          python .github/workflows/validate.py
          if [ $? -ne 0 ]; then
            echo "Validation failed"
            exit 1
          done
