# This is a basic workflow to help you get started with Actions
name: Validate Build

on:
  push:
    branches: "dev_**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Set Up Python
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install SQLFluff
      - run: pip install sqlfluff

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
      - run: |
          echo "Validating .sql files for build".
