# This is a basic workflow to help you get started with Actions
name: Validate Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Get Changed files
        id: get-changed-files
        run:
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)""
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  files:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: Return files
        run: echo ${{needs.changedfiles.outputs.ts}}
